controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\CarsController::index

car_update:
    path: /car/update
    controller: App\Controller\CarsController::update
    methods: [POST]

car_addModel:
    path: /car/addModel
    controller: App\Controller\CarsController::addModel
    methods: [POST]

car_addBrand:
    path: /car/addBrand
    controller: App\Controller\CarsController::addBrand
    methods: [POST]